# Generated by Django 4.0.8 on 2022-11-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', '維護'), ('o', '外借'), ('a', '可用'), ('r', '已預定')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
